### ISSUE TITLE
HU01: Consultar Catálogos de Álbumes

### ISSUE THREAD

**Issue by nipoanz** [MISW-4203-Apps-moviles/Proyecto-apps-moviles#1]
Como usuario visitante quiero navegar el catálogo de los álbumes para escoger lo que más me interesan

- [x] #40
- [x] #41
- [x] #42
- [x] #43
- [x] #55
- [x] #56
- [x] #44

**Comment by nipoanz** [comment]
## Criterios de Aceptación

-  Dado que soy un usuario, cuando ingreso a la sección de catálogo de álbumes, debo ver una lista de álbumes disponibles.
- Dado que soy un usuario, cuando navego por el catálogo de álbumes, puedo ver la portada de cada álbum junto con su título.
- Dado que soy un usuario, al hacer clic en un álbum del catálogo, debo ser redirigido a la página de detalles del álbum. 
-  Dado que soy un usuario, puedo filtrar los álbumes por género, año de lanzamiento, etc.

**Comment by pbohorqueza** [comment]
### Revisión
| Criterio      | Comentario       | Realizado por |
|---------------|------------------|---------------|
| Completo      | XX | XX |
| Consistente   | XX | XX |
| Negociable    | XX | XX |
| Valiosa       | XX | XX |
| Estimable     | XX | XX |
| Pequeña       | XX | XX |
| Comprobable   | XX | XX |

**Comment by oscarandresgarcia-uniandes** [comment]
![HU001 - Consultar Albumes usuario@1x](https://github.com/MISW-4203-Apps-moviles/Proyecto-apps-moviles/assets/142249468/d4696607-9dcd-4465-a2a9-5dc1ca0a5e20)

**Comment by nipoanz** [comment]
Aplicación bajo pruebas (APB) | Vinilos
-- | --
Versión/Hash commit | N/A
Ambiente de pruebas | Todas las pruebas se corren en lo siguientes dispositivos:<br><br> - Motorola Droid Maxx con Android 5 (API 21) Lollipop<br> - Samsung Galaxy S6 Edge con Android 8 (API 26) Oreo <br>- Samsung Galaxy S6 con Android 7 (API 24) Nougat |


### Escenarios de pruebas ejecutados

ID | Fecha | Tester | Funcionalidad | Requerimiento | Tipo de escenario | Nombre del escenario | API Dispositivo | Incidencia ID | Resultado
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
QA9 |  28/04/2024 | @nipoanz |  Listado de álbumes como coleccionista  | Funcional | Positivo | Navegación satisfactoria al listado de álbumes como usuario  coleccionista |  API 21 - API 24 - API 26 | N/A | Exitoso
QA10 |  28/04/2024 | @nipoanz  |  Listado de Álbumes como visitante  | Funcional | Positivo | Navegación satisfactoria al listado de álbumes como usuario  visitante |  API 21 - API 24 - API 26 | N/A | Exitoso
QA11 |  28/04/2024 | @nipoanz | Listado de Álbumes con wifi | Funcional | Positivo | Visualización correcta del listado de álbumes  con conexión wifi  |  API 21 - API 24 - API 26 | N/A | Exitoso
QA12 |  28/04/2024 | @nipoanz |  Listado de Álbumes con datos móviles  | Funcional | Positivo | Visualización correcta del listado de álbumes con datos móviles  |  API 21 - API 24 - API 26 | N/A | Exitoso
QA13 |  28/04/2024 | @nipoanz |   Listado de Álbumes sin conexión | Funcional | Negativa | Visualización incorrecta del listado de álbumes cuando no hay conexión wifi |  API 21 - API 24 - API 26 | N/A | Exitoso
QA14 |  28/04/2024 | @nipoanz |  Listado de Álbumes con pantalla en horizontal  | Funcional | Positivo | Visualización correcta del listado  de los álbumes cuando el teléfono está en posición horizontal |  API 21 - API 24 - API 26 | N/A | Exitoso
