### ISSUE TITLE
HU02: Consultar la información detallada de un Álbum

### ISSUE THREAD

**Issue by nipoanz** [MISW-4203-Apps-moviles/Proyecto-apps-moviles#2]
Como usuario visitante quiero ver el detalle de un álbum para ampliar la información sobre él

- [x] #35
- [x] #36
- [x] #37
- [x] #38
- [x] #9
- [x] #39

**Comment by nipoanz** [comment]
## Criterios de Aceptación

- Dado que soy un usuario visitante, al hacer clic en un álbum, debo ver información detallada como el nombre del artista, año de lanzamiento, lista de canciones, etc. 
- Dado que soy un usuario visitante, cuando veo la información detallada de un álbum, puedo ver la portada del álbum en tamaño completo. 
- Dado que soy un usuario visitante, puedo leer las reseñas y comentarios de otros usuarios sobre el álbum. 
- Dado que soy un usuario visitante, puedo compartir la información del álbum en redes sociales.

**Comment by pbohorqueza** [comment]
### Revisión
| Criterio      | Comentario       | Realizado por |
|---------------|------------------|---------------|
| Completo      | XX | XX |
| Consistente   | XX | XX |
| Negociable    | XX | XX |
| Valiosa       | XX | XX |
| Estimable     | XX | XX |
| Pequeña       | XX | XX |
| Comprobable   | XX | XX |

**Comment by oscarandresgarcia-uniandes** [comment]
## Comps

<img width="428" alt="HU002 - Detalle Álbum usuario visitante" src="https://github.com/MISW-4203-Apps-moviles/Proyecto-apps-moviles/assets/142249468/bce4bb89-3685-4de7-a6f5-9eca74610d69">

**Comment by pbohorqueza** [comment]
Aplicación bajo pruebas (APB) | Vinilos
-- | --
Versión/Hash commit | N/A
Ambiente de pruebas | Todas las pruebas se corren en lo siguientes dispositivos:<br><br> - Motorola Droid Maxx con Android 5 (API 21) Lollipop<br> - Samsung Galaxy S6 Edge con Android 8 (API 26) Oreo <br>- Samsung Galaxy S6 con Android 7 (API 24) Nougat |


### Escenarios de pruebas ejecutados

ID | Fecha | Tester | Funcionalidad | Requerimiento | Tipo de escenario | Nombre del escenario | API Dispositivo | Incidencia ID | Resultado
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
QA1 |  27/04/2024 | @pbohorqueza   |  Navegación al detalle de un álbum  | Funcional | Positivo | Navegación satisfactoria al  detalle de un álbum al hacer click sobre el ítem en el listado de álbumes |  API 21 | N/A | Exitoso
QA2 |  27/04/2024 | @pbohorqueza   |  Visualización detalle de un álbum - texto  | Funcional | Positivo | Visualización correcta de los detalles del álbum (título, descripción, nombre del artista, año de lanzamiento)  |  API 21 | N/A | Exitoso
QA3 |  27/04/2024 | @pbohorqueza   |  Visualización detalle de un álbum - imagen  | Funcional | Positivo | Visualización correcta de la portada del álbum en la vista de detalle  |  API 21 | N/A | Exitoso
QA4 |  27/04/2024 | @pbohorqueza   |  Visualización detalle de un álbum - imagen  | Funcional | Positivo | Visualización correcta de la portada del álbum en la vista de detalle  |  API 21 | N/A | Exitoso
QA5 |  27/04/2024 | @pbohorqueza   |  Navegación en página de detalle de un álbum  | Funcional | Positivo | Navegación vertical de la vista de detalle del álbum  |  API 21 | N/A | Exitoso
QA6 |  27/04/2024 | @pbohorqueza   |  Visualización sección de comentarios en el detalle del álbum  | Funcional | Positivo | Visualización del listado de comentarios y botón para agregar comentarios  |  API 21 | N/A | Exitoso
QA7 |  27/04/2024 | @pbohorqueza   |  Persistencia del detalle de álbum sin conexión a internet   | Funcional | Negativo | Al encontrarse en el detalle de un álbum, persiste la información si el dispositivo pierde conexión a internet |  API 21 | N/A | Exitoso
QA8 |  27/04/2024 | @pbohorqueza   |  Navegación al detalle de álbum sin conexión a internet   | Funcional | Negativo | Navegación al detalle de un álbum cuando no hay conexión a internet - aplicación sigue en funcionamiento |  API 21 | N/A | Exitoso
