### ISSUE TITLE
HU03: Consultar el listado de artistas

### ISSUE THREAD

**Issue by nipoanz** [MISW-4203-Apps-moviles/Proyecto-apps-moviles#3]
Como usuario visitante quiero ver el listado de artistas para escoger los que más me interesan

- [x] #45
- [x] #46
- [x] #47
- [x] #48
- [x] #49

**Comment by nipoanz** [comment]
- Dado que soy un usuario visitante, al acceder a la sección de artistas, debo ver una lista de todos los artistas disponibles.
- Dado que soy un usuario visitante, cuando navego por la lista de artistas, puedo ver la imagen o foto de cada artista junto con su nombre. 
- Dado que soy un usuario visitante, puedo buscar artistas por nombre o género musical. 
- Dado que soy un usuario visitante, al hacer clic en un artista, debo ser redirigido a la página de detalles del artista.

**Comment by oscarandresgarcia-uniandes** [comment]
## Comps
<img width="428" alt="HU003 - Consultar Artistas" src="https://github.com/MISW-4203-Apps-moviles/Proyecto-apps-moviles/assets/142249468/8bd92712-30d6-4254-a853-0163c08f07b1">
