### ISSUE TITLE
HU05: Consultar listado de coleccionistas

### ISSUE THREAD

**Issue by nipoanz** [MISW-4203-Apps-moviles/Proyecto-apps-moviles#5]
Como usuario visitante quiero consultar el estado de coleccionistas para seleccionar el que más me interese 
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #14

**Comment by nipoanz** [comment]
## Criterios de Aceptación

- Dado que soy un usuario visitante, al acceder a la sección de coleccionistas, debo ver una lista de todos los coleccionistas disponibles. 
- Dado que soy un usuario visitante, cuando navego por la lista de coleccionistas, puedo ver la foto o avatar de cada coleccionista junto con su nombre. 
- Dado que soy un usuario visitante, puedo buscar coleccionistas por nombre o preferencias musicales. 
- Dado que soy un usuario visitante, al hacer clic en un coleccionista, debo ser redirigido a la página de detalles del coleccionista.

**Comment by pbohorqueza** [comment]
### Revisión
| Criterio      | Comentario       | Realizado por |
|---------------|------------------|---------------|
| Completo      | XX | XX |
| Consistente   | XX | XX |
| Negociable    | XX | XX |
| Valiosa       | XX | XX |
| Estimable     | XX | XX |
| Pequeña       | XX | XX |
| Comprobable   | XX | XX |

**Comment by oscarandresgarcia-uniandes** [comment]
## Comps

<img width="428" alt="HU005 - Consultar Coleccionistas - usuario visitante" src="https://github.com/MISW-4203-Apps-moviles/Proyecto-apps-moviles/assets/142249468/269b2cc8-8433-436e-8ff7-1c04edc90171">
