### ISSUE TITLE
HU09: Comentar un Álbum

### ISSUE THREAD

**Issue by nipoanz** [MISW-4203-Apps-moviles/Proyecto-apps-moviles#8]
Como coleccionista quiero comentar un álbum para dar a conocer mi opinión sobre el álbum

- [x] #29
- [x] #30
- [x] #31
- [x] #32
- [x] #33
- [x] #123

**Comment by nipoanz** [comment]
## Criterios de Aceptación

- Dado que soy un coleccionista, cuando veo la información detallada de un álbum, debo tener la opción de agregar un comentario para expresar mi opinión sobre el álbum. 
- Dado que soy un coleccionista, al agregar un comentario, este debe aparecer visible para otros usuarios que visiten la página del álbum. 
- Dado que soy un coleccionista, puedo editar o eliminar mis propios comentarios en caso de ser necesario. 
- Dado que soy un coleccionista, puedo dar "me gusta" o "no me gusta" a los comentarios de otros usuarios.

**Comment by pbohorqueza** [comment]
### Revisión
| Criterio      | Comentario       | Realizado por |
|---------------|------------------|---------------|
| Completo      | XX | XX |
| Consistente   | XX | XX |
| Negociable    | XX | XX |
| Valiosa       | XX | XX |
| Estimable     | XX | XX |
| Pequeña       | XX | XX |
| Comprobable   | XX | XX |

**Comment by oscarandresgarcia-uniandes** [comment]
##Comps

<img width="428" alt="HU009 - Comentar álbum" src="https://github.com/MISW-4203-Apps-moviles/Proyecto-apps-moviles/assets/142249468/0158d025-9310-41f9-b992-a977f6f9174b">

<img width="428" alt="HU009 - Comentar álbum - error" src="https://github.com/MISW-4203-Apps-moviles/Proyecto-apps-moviles/assets/142249468/ca476a8c-2245-4ec4-8cea-87b582da586a">

<img width="428" alt="HU009 - Comentar álbum - form" src="https://github.com/MISW-4203-Apps-moviles/Proyecto-apps-moviles/assets/142249468/cdcba9a9-6603-4380-8e77-8121ec7b303b">
